### ISSUE TITLE
D3200 - Still limited to 30 min of Live View after patching

### ISSUE THREAD

**Issue by fpenguin** [simeonpilgrim/nikon-firmware-tools#101]
I'm trying to capture HDMI streaming from D3200 connected to HDMI capture card. 

I've downloaded the update bin file from Nikon, uploaded it to Nikon Hacker, clicked on the updates I want to add and downloaded the patched file. I renamed the patched file name from "patched_D3200_0103.bin" to "D3200_0103.bin" and copied it to the root of the SD card. The camera went through the update process and the listed firmware version on A changed from 1.04 to 1.03. On checking for the time limit and manual live view operation there is no change. I tried both Long preset and Custom setting with 30 min, and the live view gets cut at 30m mark. 

I tried repeating the process with a different browser, and from a different computer, and still no luck. :-(
Any suggestion?

**Comment by fpenguin** [comment]
I figured it out. Instead of having it set to "Long", go to Custom -> Set it to 15 min, after the patch.

**Comment by simeonpilgrim** [comment]
I have been away, but great to hear you solved the problem.

**Comment by sim992** [comment]
I did the update from your site: https://simeonpilgrim.com/nikon-patch/nikon-patch.html

But I don't understand what to set to increase standby of liveview display

**Comment by zeitseeing** [comment]
I would love to try this as well. Nikon only offers the 1.04 firmware on its site and that can't be patched, it seems. Could someone here post the patched firmware or the 1.03 firmware, so I can patch it? 🙏
