### ISSUE TITLE
Nikon D5600

### ISSUE THREAD

**Issue by kristijan97** [simeonpilgrim/nikon-firmware-tools#107]
Hey guys, I wanted to check what's the status of the Nikon D5600. Firmware for that model is not recognized.
Are you planning to support that model?
Thanks!

**Comment by SamuelPalubaCZ** [comment]
Same issue...

**Comment by simeonpilgrim** [comment]
No plans.

**Comment by SamuelPalubaCZ** [comment]
> No plans.
:((
Can i just port it from another camera type frimware?
I just need infinite video limit...

**Comment by simeonpilgrim** [comment]
> I just need infinite video limit...

so if that is hours+ of live view timer, to allow longer streaming of the video, that is rather simple in general to find.

If you want to record unlimited time wise video to the SD that will just not happen ever.
