### ISSUE TITLE
Online patch tool - Domain expired

### ISSUE THREAD

**Issue by hpingel** [simeonpilgrim/nikon-firmware-tools#115]
It looks like the domain has expired and the online patch tool is not available. Thank you for your good work!

**Comment by ian5142** [comment]
You mean this domain: http://simeonpilgrim.com/nikon-patch/nikon-patch.html or the Nikon Hacker forum, both are up for me.

**Comment by hpingel** [comment]
I checked on a different computer and there I get the right website I suppose. On an Android phone I get this - see screenshot -
![Screenshot_20210529_173338](https://user-images.githubusercontent.com/646865/120077862-695ffd00-c0a4-11eb-8e64-0483e9bb283c.jpg)
 in Chrome and in Firefoy browser

**Comment by simeonpilgrim** [comment]
The domain, is still valid for a few more years, but I have lost access to the hosting management tool. 
Cheers for the warning/headup.

Have started talking with hosting provider.

**Comment by simeonpilgrim** [comment]
for now the patching site can be reached at this cloudfront address:

https://dyk3v11u6y5ii.cloudfront.net/nikon-patch/nikon-patch.html

working on getting the domain and the rest of the site migrated.

**Comment by stevegoossens** [comment]
I also wondered what was happening with your site and just assumed "hosting issues" and built the tool site/page and hosted it at https://www.amazinggoose.com/nikon-patch/nikon-patch.html _before_ thinking to check the repo issues and finding this issue 😄 

So, good news is that your site build instructions were good enough for me to build on Mac, with a few tiny bits (the .cmd files) easily being translated to the corresponding commands that work on a non-Windows shell.

**Comment by simeonpilgrim** [comment]
> So, good news is that your site build instructions were good enough for me to build on Mac, with a few tiny bits (the .cmd files) easily being translated to the corresponding commands that work on a non-Windows shell.

Glad that .cmd files acted as the intended bread crumbs for others to follow. Even if you are gluten free.

**Comment by stevegoossens** [comment]
Haha, yeah they worked... I was too lazy to walk upstairs to use my Windows laptop and used my (work) MacBook instead.

**Comment by stevegoossens** [comment]
I'm sure there are many guides on using your Nikon Patch tool, but I think I struggled a bit to find the original firmware download and initially missed the bit about renaming the patched firmware. That's why I bothered to do a screen capture when attempting it, to present as a rambling unedited example of someone doing it for the first time.

I've just finished writing a guide to using the tool on my site at https://www.amazinggoose.com/nikon-firmware-patch/ and to make it something useful to the community, I found _all_ the download links for the Nikon original firmware and included them in the article.

Maybe this will be useful to someone :)

**Comment by simeonpilgrim** [comment]
nice work on providing links. we avoided that as at the time we were working on "current" firmware, and we want to not provide any files that violated copyright. Thus why the patch tool does the work on the client side via (originally silverlight) webassembly

**Comment by stevegoossens** [comment]
That old chestnut eh. Yeah I did something similar for an abandoned PC game (Hawken) that needed a backend for login and user profiles/inventory. 

I remade the backend API and then we provided a download of the unmodified game client, and instructions on how to edit the client config (just a text file) for the backend URL.

**Comment by simeonpilgrim** [comment]
site is up and running again, thanks again for the heads-up.
