### ISSUE TITLE
Binary tool that allows extracting and patching of firmware?

### ISSUE THREAD

**Issue by MysteriousLog6** [simeonpilgrim/nikon-firmware-tools#118]
Is there a binary tool that allows extracting and patching of the firmware?

**Comment by simeonpilgrim** [comment]
The online patch tool allows you to apply patches. If you was wanting to do patch dev then the nikon-patch c# project allows decoding bin files into the seperste firmware files, that you would want to reverse engineer

**Comment by MysteriousLog6** [comment]
By separate firmware files do you mean the FR80 and TX19 files? The emulator can extract those.

**Comment by simeonpilgrim** [comment]
> By separate firmware files do you mean the FR80 and TX19 files? 
Yes, that is what I meant.

> The emulator can extract those.
Yes, that is also true. 

But I didn't read your question as, "can the emulator do X" I read it as "how can I do X" and the tool that just does X is the easiest way to do X, in my opinion. It also happens I wrote that tool, so it's very familiar to me, and the emulator project is rather large.

But perhaps better thing to have written, is, "I do not fully understand the intent of this question, what problem are you trying to solve" and then with that information I could have provided a better scoped answer.

**Comment by MysteriousLog6** [comment]
I had actually come to know about the Emulator after seeing this project , I will try this , I have to install Visual Studio so that I can compile the project.

Improved Question:
"I would like to make custom patches with more features for the D5300 , how do you make patches?"

**Comment by simeonpilgrim** [comment]
I unpack the firmware with nikon-patch, and then reverse engineer the firmware, I used to IDA Pro, but I have been using Ghidra for the last couple of years, yikes a new version is released, I should play with that.

Then once I set of binary changes, those are added to a patch record in the same nikon-package project, from which the c/webassembly code is generated, and then copied into the nikon-patch-js project, which is what powers the online patch tool.

Visual Studio Community works, or Visual Studio Code should be able to build the tooling also.

**Comment by MysteriousLog6** [comment]
Cool! Ghidra is what I am using , It is dangerous to do this as I understand right? I might first try it on the emulator still scared to try it out on an actual device.

**Comment by simeonpilgrim** [comment]
Ah, well the emulator will not run your code, as the emulator only supported the D5100 (and with some bending other FR based CPU's).

How you "descarify" the process is spend ages working on the firmware so you are really sure what you have changed. And the also only change code that runs when you change a mode or setting etc, so it not part of the main boot cycle, thus you can still come into the menu and load a different firmware if your code works incorrectly.

**Comment by simeonpilgrim** [comment]
I just added some getting start notes here:

https://simeonpilgrim.com/blog/2021/08/07/getting-started-disassembling-nikon-firmware/

let me know if there are critical gaps that have been jumped etc etc.

**Comment by MysteriousLog6** [comment]
The guide is pretty good , but I was confused by the "first jump" part I didn't quite understand that.

**Comment by MysteriousLog6** [comment]
The firmware reset jump address is also different for me (I know different device) but instead of starting with 0x90 mine starts with 0x04? (D5300 firmware)

**Comment by simeonpilgrim** [comment]
Will look at the D5300 firmware later and confirm you finding.

**Comment by simeonpilgrim** [comment]
I have already documented the D5300 firmware loads at 9002000, but in lets look I opened the D5300 v1.02 B firmware which is called b930_102.bin, and when select ARM v7 LE the correct loading address is 0x9002000

![image](https://user-images.githubusercontent.com/3347507/128679240-4dc63595-bebe-4db8-ab73-b5b52691af04.png)

**Comment by MysteriousLog6** [comment]
I am using Ds5300 v1.03 , b930_103.bin 
Using Ghidra following the same steps this is what I get.
![image](https://user-images.githubusercontent.com/63236194/128686201-0bcd86c3-7e5b-4f36-b3bd-19b2e949f330.png)

**Comment by simeonpilgrim** [comment]
You have chosen the Big Endian processor, you need to pick ARM v7 LE

**Comment by MysteriousLog6** [comment]
> You have chosen the Big Endian processor, you need to pick ARM v7 LE
> 
> ![image](https://user-images.githubusercontent.com/3347507/128688481-c56420b6-ebf1-4c21-9c82-5ad475be6f8d.png)
> 
> see how when then byte 047c3290 are read in the other order 90327c04 it works better.

Yep now it works
