### ISSUE TITLE
Nikon d3300

### ISSUE THREAD

**Issue by Resphapiness** [simeonpilgrim/nikon-firmware-tools#127]
This would be a very great help if you could provide old firmware for nikon d3300, which was c - 1.00 and L -2.002. I updated firmware to c - 1.02 and L - 2.018 and then image quality is totally bad. I then found c - 1.01 and downgraded to it and still the same problem with image quality.

If you could help me getting C - 1.00 and L - 2.002, I would be really grateful.

With thanks.

**Comment by simeonpilgrim** [comment]
As noted privately,  the 1.00 firmware is not publicly released by Nikon, and yes in theory it can be reconstructed off an existing camera, but I don't have one to clone the firmware off, I also honestly suspect Nikon will not have made quality worse in an update. 

So I am not interested in the level of effort of this task.
