### ISSUE TITLE
d7000, hdmi live view, Discussion continuation from youtube

### ISSUE THREAD

**Issue by teodoryantcheff** [simeonpilgrim/nikon-firmware-tools#129]
This is a continuation of the youtube comments [here](https://www.youtube.com/watch?v=inIBjEleJAA&lc=UggeZe7DXN0p8XgCoAEC.7-H0Z7-IIpz9hDORxP6fWS)

Just to have it here as well -- the camera discussed is a d7000.

* Firmware "configured" as follows:

![image](https://user-images.githubusercontent.com/4791195/196180301-dd721c24-097e-4740-bf7d-d96237e8bf49.png)

* HDMI set to 720p, Movie settings set to **720p24**:

Live view:
![image](https://user-images.githubusercontent.com/4791195/196210555-d8b53f9d-b6b2-4941-a545-55f6379d7343.png)

Settings menu:
![image](https://user-images.githubusercontent.com/4791195/196208230-f538592e-dad2-430b-bef3-562c99f56087.png)

* HDMI set to 720p, Movie settings set to **720p25**:

Live view:
![image](https://user-images.githubusercontent.com/4791195/196208537-0146658a-cded-4550-bd9c-02d55a337b28.png)

Settings menu:
![image](https://user-images.githubusercontent.com/4791195/196208863-3d13831e-8ec7-4476-844f-73fea839af64.png)

* Setting HDMI output to 1080i, changes only the menu view:
![image](https://user-images.githubusercontent.com/4791195/196209236-6244f7ae-d8f9-4759-910a-1a13afd62611.png)

and LiveView output remains the same, cropped one. I do not have 30p mode in Movie settings - only those:
![image](https://user-images.githubusercontent.com/4791195/196213976-5d30909b-1d50-4256-a6cb-c2f1e64a86a3.png)

When the firmware is configured with the "Clean HDMI & LCD Liveview" option any display elements are removed from LiveView but unfortunately, the output image remains cropped (thick black borders, image centered on a full-hd panel) no matter what HDMI and Movie settings I use.

Another thing I noticed while testing is these 2 squares on the screen:
![image](https://user-images.githubusercontent.com/4791195/196212400-0ed7c681-5f6d-4205-aa82-f9ed31dddb42.png)

The black one can be moved with the "arrow buttons" on the back of the camera, but the location it is at on the screenshot is as far as it goes both to the right and bottom.

This may be obvious but my aim is to have a clean, no display elements full hd stream output to HDMI with the idea of capturing that externally. I'm looking at using the camera as a long-duration webcast/streaming camera -- that is recording times way longer than even the un-locked max recording times.

*How unreasonable is the goal I'm chasing?
*Am I wrong to assume that **1080p** HDMI is not possible on the d7000 ? 
*What is the intended behavior of the "HDMI Output 720p FullScreen" option? Since coming to think of it, I think I'm not completely sure if my expectations are not way off.

Many thanks for taking the time to help and kudos for the amazing piece of work you've done!

**Comment by simeonpilgrim** [comment]
If you change the camera to NTCS mode instead of PAL 

https://nikonimglib.com/snbrkm/onlinehelp/en/km360/reference_manual/05_settings_02.html#ntsc_pal

Then you should have 720p 30 available, which just makes more sense for a webcam, and I am very sure that is the mode required to have "full screen"

**Comment by teodoryantcheff** [comment]
With the output set to NTSC, 30 fps modes do become available. However:

![image](https://user-images.githubusercontent.com/4791195/196372543-e8f99577-9c5d-48e4-a1b9-42c2986b657b.png)

I.e. the image is still not full-screen.

Am I wrong to think that **1080p** is **not** possible on the HDMI out with a d7000? 

Also, the "HDMI Output 720p FullScreen" option -- what does it really do? I mean what is the expected behaviour -- have a flag in the bitsream forcing the output device to ...."_upscale_" the 720p stream to its max resolution or something else? Please help me understand.

I think that the next best is to use 720p@24fps output on HDMI for recording (provided 1080p is not an option). And for using an external monitor to monitor (doh) Live View will have to be stretched to full-screen by the monitor itself and not in the camera.


Many thanks again, Simeon!

**Comment by simeonpilgrim** [comment]
the camera hardware scales/clips the sensor to the HDMI output size, at the rate of your fps. Not sure why you want a 24 fps webcam over a 30fps, but knock yourself out.

The patch altered the scaling to make the sensor throw less pixels away (in effect).

**Comment by teodoryantcheff** [comment]
If 30 is the only working option I'd obviously take that. But as you see in the photo above 720p30 is also not "full-screen".

**Comment by teodoryantcheff** [comment]
Many thanks for the time taken to talk to me, @simeonpilgrim !
I will close the ticket now.
