### ISSUE TITLE
unable to reverse hacks

### ISSUE THREAD

**Issue by ProHyphonzDaCoder** [simeonpilgrim/nikon-firmware-tools#135]
How do I reverse the hacks?

**Comment by simeonpilgrim** [comment]
what do you mean by reverse the hacks? 

Do you mean revert the firmware to normal? Then just put the unalter firmware on the SD card and install it on your camera

**Comment by ProHyphonzDaCoder** [comment]
Thanks I figured it out 2 hours later :)
