### ISSUE TITLE
Nikon Hacker forums down

### ISSUE THREAD

**Issue by lexd0g** [simeonpilgrim/nikon-firmware-tools#138]
Dunno if this is the wrong place, but the Nikon Hacker website appears to be down since yesterday, it just redirects to a generic Virtualmin domain parked website. The Wayback Machine [crawled](https://web.archive.org/web/20231101101020/http://nikonhacker.com/robots.txt) the now-inexistent robots.txt file on Nov 1st, so it's quite recent.

**Comment by simeonpilgrim** [comment]
As [noted on my blog](https://simeonpilgrim.com/blog/2023/11/20/nikonhacker.com%20update/) 

> This post is just to let people know, we know nikonhacker.com is down. Max has been hosting the site since 2011, and it was a wonderful resource.
> 
> But it was running on phpBB and over time it became a security problem, this is why for years you could not post new content, as the compatible version of php (5.x) was no longer safe to leave on the internet. The effort to get it all working felt like it was more than my interest in hacking camera’s.
>
>Anyways, changes by Max’s hosting service provider now mean those hosts do not exist, and thus it was agreed due to the read-only nature that a redirect to archive.org would be an acceptable level of effort/value trade off.
>
> https://web.archive.org/web/20230925033615/https://nikonhacker.com/
