### ISSUE TITLE
Nikon D5600 Frimware not recognized

### ISSUE THREAD

**Issue by SamuelPalubaCZ** [simeonpilgrim/nikon-firmware-tools#140]
![image](https://github.com/simeonpilgrim/nikon-firmware-tools/assets/63147933/9d739a96-1326-43f3-a6c1-b753c84f2475)

**Comment by simeonpilgrim** [comment]
as the text say, "this firmware file is recognised", so your ticket is just wrong. The second part of the message also states, "there is not patches availible for this Model/Version" mean "there are no patches".

So maybe your point is `availible ` is spelt wrong.
