### ISSUE TITLE
Nikon D5100 still only 15 mins of Liveview after patching

### ISSUE THREAD

**Issue by plamf** [simeonpilgrim/nikon-firmware-tools#144]
I don't see any other options to increase the Liveview duration in the options after patching.
Liveview turns off exactly after 15 minutes.

I'm using HDMI Out into a USB Capture Card.

**Comment by simeonpilgrim** [comment]
I will assume you used the `Liveview - 3 mins to 6 hours` patch, which changes the 3 minute time to be 6 hours. Thus if "you still have a 15 minute timeout" I am guessing your setttings are on the "15 minute" timer, not the "3 minute timer". Please try the 3 minute timer,
