### ISSUE TITLE
NTool not work

### ISSUE THREAD

**Issue by ECS-tasy** [simeonpilgrim/nikon-firmware-tools#145]
Hi Simeon. Thanks for your nikon-firmware-tools.

I am trying to decrypt D810 firmware and split it into A+B.
But NTool not work. 
![ntool2_39hX2hyeTR](https://github.com/simeonpilgrim/nikon-firmware-tools/assets/32937694/394e4afb-af7b-443d-b3e2-0a49f360fb0f)

I download it form https://www.personal-view.com/talks/discussion/1494/nikon-firmware-is-decrypted-my-tool-inside/
Do you have any suggestions?

**Comment by simeonpilgrim** [comment]
N-tool was developed by a person coping the work of the Nikon Hacker team, so the fact it doesn't work for a D810 brings me delight. But sounding less petty, the tools inside this repository will open that file.

**Comment by simeonpilgrim** [comment]
I see you have run the LocalUI dev tool, and ported the patches correctly it seems. Nice.
