### ISSUE TITLE
D7200 firmware decoder

### ISSUE THREAD

**Issue by joxeankoret** [simeonpilgrim/nikon-firmware-tools#76]
Hi,

I cannot find a way to use the firmware decoder for my D7200 firmware. Is it supported? If not, can you give me some tip to determine what I need to do in order to get it?

Thanks in advance!

**Comment by simeonpilgrim** [comment]
I cannot see a D7200 firmware, so not sure where you got one to test with...

**Comment by joxeankoret** [comment]
From here: http://downloadcenter.nikonimglib.com/en/products/197/D7200.html
Once you have extracted the contents (you don't need to execute the installer) you get the file "DCDATAUpdate\NKLD0213.BIN".

**Comment by simeonpilgrim** [comment]
Ah that's a lens correction pack, not a firmware. Those decode with DecryptNKLDFile
