### ISSUE TITLE
D3300 Video 1080 HQ 64mbps Bit-rate not working

### ISSUE THREAD

**Issue by megapro17** [simeonpilgrim/nikon-firmware-tools#78]
I recorded two videos, with patch and without. Videos are the same. Both 38mbps, and approximately same size. What I do wrong? I selected max quality in settings, 1080p60 High

**Comment by simeonpilgrim** [comment]
given the old value was 24Mbps if you are getting 38Mbps I would suggest you were running the patched firmware.. both times, and it is working...

On the D3300 the daterate is an upper bound used by the VBR encoder, thus if there is only 38Mbps of data in the scene 38Mbps will be used, where as if the scene has 38Mbps of data and the limit is 24Mbps, the camera will compress it to fit within the data limit. To get the higher bitrates to need more happening in the scene, so ether shake the camera to induce a larger amount of change in the frame or also have high ISO so there is a lot of grain across pixels.

**Comment by megapro17** [comment]
No, both times I got the same video, as the size was identical.
The video was with shaking hands, bitrate should rise up. 
Are you sure, that patch works with NTSC 60 fps mode? I'll check it with PAL 50 fps later.

**Comment by simeonpilgrim** [comment]
No I am not sure, as I have personally never tested the patch on that camera model. For today you are the expert of this. I bow to your knowledge.

**Comment by megapro17** [comment]
Sorry for late answer. 
I tested again, and found, that bitrate goes up to 64mbps when is 60/50 fps is not selected. Video footage was approximately the same. I was shaking camera around art. Capture settings was 1080p, high quality. 

Here is mediainfo:
1) Duration                                 : 8 s 809 ms
Bit rate                                 : 57.9 Mb/s
Frame rate                               : 29.970 (30000/1001) FPS
2) Duration                                 : 8 s 383 ms
Bit rate                                 : 48.3 Mb/s
Frame rate                               : 23.976 (24000/1001) FPS

And higher frame rate that have lower bitrate

1) Duration                                 : 20 s 170 ms
Bit rate                                 : 37.4 Mb/s
Frame rate                               : 59.940 (60000/1001) FPS
2) Duration                                 : 5 s 460 ms
Bit rate                                 : 36.3 Mb/s
Frame rate                               : 50.000 FPS

**Comment by megapro17** [comment]
Please answer me...

**Comment by simeonpilgrim** [comment]
That is interesting that the frame rate plays a role in the compression ratio's.

Yes you can ask, but just like every other person that has asked, for the newer camera's it's not as simple as it seems, as we did not find a working solution to the problem. 

If you notice I have not actively worked on this project for a couple of years. And if I where it would be on this camera model, so while it should be applicable, my interests in endless patch porting is super low.

Also exfat support is present on all camera's, so with that extra context, as per prior statements, there are internal counts that are 32bit, so safely overflowing the file offsets is not as simple as it is to conceive of..
