### ISSUE TITLE
D800 1.11 Firmware Patch

### ISSUE THREAD

**Issue by ssj92** [simeonpilgrim/nikon-firmware-tools#81]
Hi, the online patch tool isn't compatible with 1.11 firmware which was released last year. 

It adds support for AF-P lens so I was wondering if there is any way to update the online patch tool to also support this firmware?

Thank You

**Comment by crazyfish1111** [comment]
http://simeonpilgrim.com/nikon-patch/nikon-patch.html is not work for my d800 1.10. I want to crack my D800 64m firmware。But is not work。i use chrome and safari for my mac 10.12.6.and use ie11 and chrome for my win70-64bit。it's not work。how to use d800 64m。help me。please。

**Comment by crazyfish1111** [comment]
https://nikonhacker.com/ is not work too

**Comment by simeonpilgrim** [comment]
> https://nikonhacker.com/ is not work too

seems to be working presently. But it has it's moments.

**Comment by simeonpilgrim** [comment]
> http://simeonpilgrim.com/nikon-patch/nikon-patch.html is not work for my d800 1.10. I want to crack my D800 64m firmware。But is not work。i use chrome and safari for my mac 10.12.6.and use ie11 and chrome for my win70-64bit。it's not work。how to use d800 64m。help me。please。

Hi Crazy, the site is working for me, so I am not sure what your experience is. At what point do your experience it diverging from your expectations.

Does the web-assembly application load? 
Can it select your file? 
Is your file recognised?
Can you select the patches you want?
Can you save the patch file?
Can you find the patch on your SD card to install the firmware?
How are you testing the patch works or doesn't?

**Comment by crazyfish1111** [comment]
sorry maybe my pc have problem.my camera is d800.can you give me the fireware(1.11) of path.my mail:crazyfish1111@gmail.com 
Video 1080 HQ 64mbps Bit-rate NQ old HQ and  Video 1080 HQ 64mbps, NQ 36mbps

**Comment by simeonpilgrim** [comment]
sorry we do not send patched firmware.
