### ISSUE TITLE
D3300 - No 15 minutes liveview timeout patch

### ISSUE THREAD

**Issue by davidgfb** [simeonpilgrim/nikon-firmware-tools#96]
Citating #91. Thank you for uploading the patch!
Are both D3300 patches, 64 mbps video and no 15 minutes live view timeout, compatible between them? Can they coexist at the same time, firmware update or patch? When will they be rised to beta? The 64 mbps video patch for the D3300 has been more than 2 years in alpha

Has anyone, @deccosantos, tried the "no 15 minutes liveview timeout" patch yet in his D3300? Does it work well?

**Comment by deccosantos** [comment]
Hi. At the moment I didn't try the patch. But I will try and i gonna say something here. I have a question, for example, if I set this patch to have no limits in live view, and I set my cam to record longer than 15 min in live view, can I burn the sensor or this is just a limitation to develepers pay less?

**Comment by davidgfb** [comment]
Hi. Afaik the D3300 as other DSLR’s has a maximum recording time of 29.59 minutes, expected to be patched in this camera, in 24p low quality. The major limiting factor is the fat32 sd card format which only supports a maximum individual file size of 4gb and is also a legal way of  the trademark of paying less money in taxes considering the D3300 a photo camera and not a video camera. The solution here would be to save an “endless” video sliced or divided in multiple 4gb files. The D3300 has a maximum temperature    shutdown which can be avoided with a battery grip or ac adapter cord. I hope you luck trying the patch but it’s an alpha so it should be fine! Hoping to hear from more people trying this patches in theirs d3300’s

**Comment by simeonpilgrim** [comment]
> if I set this patch to have no limits in live view, and I set my cam to record longer than 15 min in live view, can I burn the sensor or this is just a limitation to develepers pay less?

All Nikon DSLRs have heat sensors in the camera's and the camera will stop record, and refused to start recording if the camera is over heated. So from a "will if catch on fire, burn out" perspective, there is no difference to leaving your camera outside in the sun at 40/110 degrees and then trying to use it (btw this will make it too hot) and running it in a cold environment for hours, and it getting to the same temperature. 

It's all about moving heat. Anyways the lower end D3x00 camera's tend to not be as good at moving heat, so will tend to over heat and self turn off, as noted elsewhere on the youtube, pointing a fan at your camera is a very good idea to help remove excess heat.

**Comment by simeonpilgrim** [comment]
> Are both D3300 patches, 64 mbps video and no 15 minutes live view timeout, compatible between them? 
Yes. But they will not function at the same time, as the first is in effect when recording, and the latter is in effect pre-recording.
But the patching tool has code to handle patches that are exclusive, and not allow them to both be selected (or applied).

> Can they coexist at the same time, firmware update or patch? 
Ah I got ahead of myself, see above.

> When will they be rised to beta? (the 64 mbps video patch for the D3300 has been more than 2 years in alpha)
When I change the status of them. Also when I get asked/reminded and find some evidence that they have to used. Both these patches are super low risk, from a bricking perspective, thus they should really have started life as BETA's as that are both not critical path on the load/update path, thus cannot block the re-flashing of alternative firmware in the case of failure.

> Has anyone (@deccosantos) tried the "no 15 minutes liveview timeout" patch yet in his D3300? Does it work well?

Well I can look at stats to see how much is has been patched, but not if people have flashed it onto their camera.. But I suspect seems it's the same code in 4+ firmware's, and it's just a timer value, its works completely perfectly. Thus could be promoted to Released.

**Comment by simeonpilgrim** [comment]
> Hi. Afaik the D3300 as other DSLR’s has a maximum recording time of 29.59 minutes, expected to be patched in this camera, in 24p low quality. The major limiting factor is the fat32 sd card format which only supports a maximum individual file size of 4gb and is also a legal way of the trademark of paying less money in taxes considering the D3300 a photo camera and not a video camera. The solution here would be to save an “endless” video sliced or divided in multiple 4gb files. 
This is not the answer to the question you or deccosantos asked. And is fundamentally wrong.

The limit is not a filesystem limit, the limit is a code limit in the movie recording firmware. The code the decides where to record next block of data uses a 32bit number (thus 4gb) and when it talks to the file layer that number is expanded to  64bit number. So it's not the filesystem but the code that needs rewriting, but the movie pipeline, and possible the file package itself. Anyways it actually doesn't matter, it too much effort and just not going to happen.

The 29.59 minute does appear to be a device classification limit, but that is work around able, the problem is `size = time * bitrate`. So if you want higher bitrate you get less time.

> The D3300 has a maximum temperature shutdown which can be avoided with a battery grip or ac adapter cord. 
This is very untrue. It is true there is temperature code to stop overheating, the battery grip/ac adapter do nothing to interact with this, *besides* moving some thermal mass/load further away. The camera only cares about heat at the sensor. Thus a fan is also effective. But it is a very good idea if you are going to do lots of live recording to get an AC adapter just to avoid thrashing the battery, and to have longer shot life time.

**Comment by davidgfb** [comment]
Hi @deccosantos 
Could you try the patch? 
Thank you

**Comment by davidgfb** [comment]
Ok so I have tested both patches at once, thanks to commentator Enrique AQ at youtube that did it before me, and they work. I have found that auto-off timer menu which the one I was not familiarized with. I did set it to custom 15 mins lv and is working correctly their 6h if I remember well. Also I've found that, with high lights overexposed and lots of moving video, 1080p@60 normal quality works at higher bitrates than the same at hq or 30 fps hq and 24 fps hq, reaching about 58.32 mbps video. More than 3x times more info from the sensor from previous video files. Thanks again @simeonpilgrim for your support and great job!

**Comment by odlg** [comment]
After patching my D3300 has no liveview timeout when 15 min is selected.

**Comment by davidgfb** [comment]
Exactly

**Comment by mako220** [comment]
> Exactly

So you mean this camera has both clean hdmi and unlimited live view not after flashing modified firmware? Sorry if I sound dumb but just wanted to make sure before buying it used.

**Comment by odlg** [comment]
Yes, the D3300 has unlimited live with this patch. It already has clean HDMI output.
